# title: Sai Sarvade
# # logo: /assets/img/headshot_circle.png
# #description: text below image
# theme: jekyll-theme-minimal

title: Sai Sarvade
description: Data & DataOps Engineer
baseurl: "" # subpath of your site, e.g., /blog
url: "https://yourusername.github.io" # replace with your GitHub Pages URL

# Theme settings
remote_theme: cotes2020/jekyll-theme-chirpy # A clean, modern theme with dark mode

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

# Author information
author:
  name: Sai S Sarvade
  avatar: /assets/img/avatar.jpg # Add your profile photo here
  email: sai.s.sarvade@gmail.com
  social:
    github: your-github-username
    linkedin: saisarvade

# Appearance
theme_mode: dark # Default to dark mode
logo: /assets/img/logo.png # Add a logo if desired
toc: true # Show a table of contents for posts/pages

# Navigation bar
navbar:
  home: /
  about: /about/
  projects: /projects/

# Footer
footer:
  text: "© 2025 Sai Sarvade. All rights reserved."
  social_links:
    - label: GitHub
      icon: fab fa-github
      link: https://github.com/your-github-username
    - label: LinkedIn
      icon: fab fa-linkedin
      link: https://linkedin.com/in/saisarvade

# Custom settings
profession: Data Engineer
location: Atlanta, GA
google_analytics: # Add your Google Analytics ID if applicable


---
