# title: Sai Sarvade
# # logo: /assets/img/headshot_circle.png
# #description: text below image
# theme: jekyll-theme-minimal


title: Sai Sarvade
description: Data & DataOps Engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Theme settings
remote_theme: pmarsceill/just-the-docs # Switching to a more robust theme suitable for portfolios
just_the_docs:
  color_scheme: dark
  logo: /assets/images/logo.png # Add a custom logo if desired
  aux_links: # Social media and other links
    LinkedIn:
      - https://linkedin.com/in/saisarvade
    GitHub:
      - https://github.com/your-github-username

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Site settings
author:
  name: Sai S Sarvade
  email: sai.s.sarvade@gmail.com
  
# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/
  - assets/images # Add your custom images here
  
# Custom variables
profession: Data Engineer
location: Atlanta, GA
email: sai.s.sarvade@gmail.com
linkedin: https://linkedin.com/in/saisarvade
github: https://github.com/your-github-username

# Analytics (you can add your Google Analytics ID here)
google_analytics: # your google analytics id

---
