# title: Sai Sarvade
# # logo: /assets/img/headshot_circle.png
# #description: text below image
# theme: jekyll-theme-minimal

# _config.yml
title: Sai Sarvade
description: Data & DataOps Engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Theme settings
remote_theme: jekyll-theme-minimal
minima:
  skin: dark
  social_links:
    linkedin: saisarvade
    github: your-github-username
  
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Site settings
author:
  name: Sai S Sarvade
  email: sai.s.sarvade@gmail.com
  
# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/
  
# Custom variables
profession: Data Engineer
location: Atlanta, GA
phone: (470)-301-1437

# Analytics (you can add your Google Analytics ID here)
google_analytics: # your google analytics id

---
